services:
  devpi-server:
    build: .
    init: true
    container_name: devpi-server
    restart: on-failure:3
    ports:
      - "3141:3141"
    volumes:
      - devpi_server_vol:/var/cache/devpi-server

volumes:
  devpi_server_vol:
