services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - docker_registry_vol:/var/lib/registry
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
  registry-browser:
    image: klausmeyer/docker-registry-browser:latest
    container_name: docker-registry-browser
    restart: always
    environment:
      - DOCKER_REGISTRY_URL=http://docker-registry:5000/v2
      - SECRET_KEY_BASE=123456
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - docker-registry

volumes:
  docker_registry_vol:
