services:
  apt-cacher-ng:
    build: .
    container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - apt_cacher_ng_vol:/var/cache/apt-cacher-ng
    restart: always
    environment:
      - CACHE_MAX_SIZE=10G
volumes:
  apt_cacher_ng_vol:
