services:
  nginx-reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./redirect.conf:/etc/nginx/conf.d/default.conf:ro
    restart: on-failure:3
